### ISSUE TITLE
Which directory is corresponding to the program split listed in Table 2?

### ISSUE THREAD

**Issue by zxteloiv** [inbaroren/improving-compgen-in-semparse#1]
Hi there,
Thank you for kindly sharing the data and code in the repo. I'm doing similar experiments on the datasets following the paper. But I'm confused about the several dataset split in the repo.
As I've checked, the new_question_split are exactly the same as i.i.d in Table 2. But the statistics differ much for the program splits.
For example, Table 2 says prog. split for GeoQuery is 424/91/91, but what I found is 642/115/159 by the following script
```bash
cat schema_full_split/aligned_train.json | jq '[.[] | .sentences[]] | length';
cat schema_full_split/final_dev.json | jq '[.[] | .sentences[]] | length';
cat schema_full_split/final_test.json | jq '[.[] | .sentences[]] | length'
```
Similarly for ATIS, the reported program split is 3061 / 373 / 375, but mine is 4402 / 437 / 423.

If my understanding is right, when m questions match n SQL, only the first SQL is used but all the questions are used (the same as Finegan-Dollak et al. 2018).
I'm not sure what's wrong with my work, could you please help clarify the settings?

Thank you very much and wish you a good day.

**Comment by inbaroren** [comment]
Hi, 
The data files are read using a dataset_reader, which filters out some of the examples (remove duplications, some examples are marked with "exclude"). You can see its logic here: https://github.com/inbaroren/improving-compgen-in-semparse/blob/06463b94f3d1b291759c08783d5a8661e2960f2e/text2sql/data/dataset_readers/dataset_utils/text2sql_utils.py#L385

Hope this solves you issue.

**Comment by zxteloiv** [comment]
Oh yes!
I've checked the number is correct now.
Thanks very much!
